import { TASK_STATES, type TaskState } from "../contracts.js";
const edges: Partial<Record<TaskState, TaskState[]>> = {
  TASK_RECEIVED: ["TASK_CLASSIFIED"],
  TASK_CLASSIFIED: ["TASK_SENSE_COMPLETE", "IMPLEMENTATION_RUNNING"],
  TASK_SENSE_COMPLETE: ["DISCOVERY_COMPLETE"],
  DISCOVERY_COMPLETE: ["FLOW_COMPLETE"],
  FLOW_COMPLETE: ["TRUTH_VERIFIED"],
  TRUTH_VERIFIED: ["GAP_DEFINED"],
  GAP_DEFINED: ["PROPOSAL_CREATED"],
  PROPOSAL_CREATED: ["PROPOSAL_APPROVED"],
  PROPOSAL_APPROVED: [
    "API_CONTRACT_REQUIRED",
    "VISUAL_REVIEW_REQUIRED",
    "IMPLEMENTATION_RUNNING",
  ],
  API_CONTRACT_REQUIRED: ["API_CONTRACT_DEFINED"],
  API_CONTRACT_DEFINED: ["API_CONTRACT_REVIEWED"],
  API_CONTRACT_REVIEWED: ["API_CONTRACT_LOCKED"],
  API_CONTRACT_LOCKED: ["VISUAL_REVIEW_REQUIRED", "IMPLEMENTATION_RUNNING"],
  VISUAL_REVIEW_REQUIRED: ["WAITING_FOR_VISUAL_APPROVAL"],
  WAITING_FOR_VISUAL_APPROVAL: ["VISUAL_LOCKED"],
  VISUAL_LOCKED: ["API_CONTRACT_REQUIRED", "IMPLEMENTATION_RUNNING"],
  IMPLEMENTATION_RUNNING: ["LOCAL_VERIFICATION"],
  LOCAL_VERIFICATION: ["INTEGRATION", "ADVERSARIAL_REVIEW"],
  INTEGRATION: ["FEATURE_E2E", "ADVERSARIAL_REVIEW"],
  FEATURE_E2E: ["UX_REVIEW", "ADVERSARIAL_REVIEW"],
  UX_REVIEW: ["ADVERSARIAL_REVIEW"],
  ADVERSARIAL_REVIEW: ["REVIEW_GATE_APPLY", "IMPLEMENTATION_RUNNING"],
  REVIEW_GATE_APPLY: ["DONE", "IMPLEMENTATION_RUNNING"],
};
export function assertTransition(from: TaskState, to: TaskState): void {
  if (
    !TASK_STATES.includes(to) ||
    from === "DONE" ||
    from === "FAILED" ||
    from === "BLOCKED" ||
    !(edges[from]?.includes(to) || to === "BLOCKED" || to === "FAILED")
  )
    throw new Error(`INVALID_STATE_TRANSITION: ${from} -> ${to}`);
}
